[package]
name = "ui"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "rust-recovery-ui"
path = "src/main.rs"

[dependencies]
iced.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

device_detector = { path = "../../crates/device_detector" }
file_carver = { path = "../../crates/file_carver", features = ["parallel"] }
recovery_engine = { path = "../../crates/recovery_engine" }
rfd = "0.14"
iced_fonts = { version = "0.3.0", features = ["bootstrap"] }
